module.exports = [
  'ltorkcontrols',
  'ltork controls',
  'ltork controls electrical actuators',
  'ltork limit switch manufacturer',
  'ltork controls Arakkonam',
  'ltork controls Tamil Nadu',
  'electrical actuator manufacturer India',
  'limit switch supplier India',
  'industrial automation products India',
  'control panel manufacturer Tamil Nadu',
  'ltork controls industrial automation',
  'electrical actuator site services India',
  'GeM tender electrical components',
  'ltork controls contact number',
  'industrial switchgear supplier India',
  'motor control centre manufacturer India',
  'PLC control panel manufacturer India',
  'MCC panel supplier Tamil Nadu',
  'ltork controls product catalogue',
  'electrical actuator price India B2B',
]
